# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_feature_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='priority',
            field=models.PositiveIntegerField(),
        ),
    ]
